INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (1, N'Beton armat', 0.15, 1.74)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (2, N'BCA', 0.3, 0.27)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (3, N'Mortar de ciment', 0.02, 0.93)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (4, N'Mortar de ciment si var', 0.03, 0.87)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (5, N'Mortar de var', 0.02, 0.7)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (6, N'Vata minerala', 0.03, 0.042)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (7, N'Pamant vegetal in stare umeda', 0.1, 1.16)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (8, N'Lemn de pin si brad', 0.08, 0.17)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (9, N'Lemn de stejar si fag', 0.08, 0.23)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (10, N'Zidarie din caramizi pline', 0.1, 0.8)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (11, N'Zidarie din caramizi GVP', 0.1, 0.7)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (12, N'Zidarie din caramizi cu goluri mari', 0.1, 0.46)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (13, N'Zidarie din BCA', 0.13, 0.3)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (14, N'Otel de constructii', 0.1, 58)
INSERT INTO [dbo].[Strat] ([Id], [Material], [Grosime], [Lambda]) VALUES (15, N'Polistiren celular', 0.1, 0.044)

